### ISSUE TITLE
Массив начинается с 0

### ISSUE THREAD

**Issue by FlameFlameFlame** [FlameFlameFlame/MPEI_Eurobot2018#3]
https://github.com/FlameFlameFlame/MPEI_Eurobot2018/blob/1d036ce6e450651d8a81b55f478998d37cc38df6/arduino/robot1/navigation/ulra_sonic_detector.ino#L10

@ODN13

**Comment by MASLINQUE** [comment]
Закрываю, в связи с переделыванием логики датчиков
